# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=40)),
                ('upwd', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('recipients', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
